name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '9.3.1'
        cache-disabled: true

    - name: Build Android APK
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process -Xmx3072m"
      run: |
        if [ -d "android" ]; then
          cd android
        fi

        if [ -f "gradlew" ]; then
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --no-daemon
        else
          gradle assembleDebug --stacktrace --no-daemon
        fi

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: Circle-Bazar-App-APK
        path: "**/build/outputs/apk/debug/*.apk"
